import { LanguageCode, TranslationDictionary, SUPPORTED_LANGUAGES } from '../types/i18n';

const en: TranslationDictionary = {
  appName: 'Aetheria Online',
  appSubtitle: 'Fantasy RPG Engine & Account System',
  navHome: 'Overview',
  navLogin: 'Account & Login',
  navCharacters: 'Characters',
  navAudio: 'Audio & Music',
  navSecurity: 'Security & JWT',
  navCloud: 'Cloud Save & Sync',
  navSettings: 'Game Settings',

  selectLanguageTitle: 'Select Your Language',
  selectLanguageDesc: 'Choose your preferred language for UI, dialogues, and system text.',
  confirmLanguage: 'Confirm & Continue',
  changeLanguageAnytime: 'You can change language anytime in Settings without restarting.',
  currentLanguage: 'Current Language',
  voiceOverLanguage: 'Voice-over Language',
  subtitleLanguage: 'Subtitle Language',
  formattingPreview: 'Locale Formatting Sample',
  sampleDate: 'Formatted Date',
  sampleCurrency: 'Formatted Currency',
  sampleNumber: 'Formatted Gold',

  loginTitle: 'Account Authentication',
  registerTitle: 'Create New Account',
  guestLogin: 'Quick Play as Guest',
  emailLabel: 'Email Address',
  passwordLabel: 'Password',
  rememberMe: 'Remember Me',
  forgotPassword: 'Forgot Password?',
  loginButton: 'Sign In',
  registerButton: 'Create Account',
  logoutButton: 'Sign Out',
  socialLoginOr: 'or connect with',
  loginWithGoogle: 'Google',
  loginWithApple: 'Apple ID',
  loginWithFacebook: 'Facebook',
  loginWithDiscord: 'Discord',
  twoFactorAuth: 'Two-Factor Authentication (2FA)',
  enter2FACode: 'Enter 6-Digit Authenticator Code',
  verify2FA: 'Verify & Login',
  sendResetLink: 'Send Password Reset Email',
  resetPasswordTitle: 'Reset Your Password',
  enterVerificationCode: 'Enter Verification Code',
  accountLockedTitle: 'Account Temporarily Locked',
  accountLockedDesc: 'Too many failed attempts. Please try again after the cooldown timer expires.',
  rateLimitWarning: 'Rate Limit Warning: Too many requests. Cooldown active.',
  guestNotice: 'Playing as Guest. Progress is cached locally. Link an email or social account to enable Cloud Sync.',

  sessionManagement: 'Session & Device Management',
  activeDevices: 'Active Logged In Devices',
  currentDevice: 'This Device (Current)',
  revokeSession: 'Revoke Session',
  revokeAllSessions: 'Sign Out All Other Devices',
  lastActive: 'Last Active',
  ipAddress: 'IP Address',

  characterSelectTitle: 'Character Selection Hub',
  createCharacter: 'Create Character',
  deleteCharacter: 'Delete Character',
  deleteConfirmationTitle: 'Confirm Character Deletion',
  deleteConfirmationDesc: 'This action is irreversible. All items and level progress for this character will be erased.',
  typeCharacterNameToConfirm: 'Type character name to confirm deletion:',
  renameTicketTitle: 'Character Rename Ticket',
  useRenameTicket: 'Use Rename Ticket',
  newCharacterName: 'Enter New Character Name',
  characterClass: 'Class',
  level: 'Level',
  stats: 'Attributes & Combat Stats',
  customizeAppearance: 'Visual Customization',
  hairColor: 'Hair Style & Color',
  outfitColor: 'Armor & Outfit Shade',
  weaponGlow: 'Aura / Weapon Glow',
  serverSelect: 'Realm / Server',

  audioSettingsTitle: 'Adaptive Music & Audio Engine',
  masterVolume: 'Master Volume',
  musicVolume: 'Music Volume',
  ambientVolume: 'Ambient Sounds',
  voiceVolume: 'Voice-Over Volume',
  uiVolume: 'UI Effects Volume',
  currentZone: 'Active Region / Zone',
  selectZone: 'Change Region Soundtrack',
  musicStyle: 'Current Musical Style',
  ambientSounds: 'Ambient Environment Layers',
  environmentalReverb: 'Acoustic Environment Reverb',
  spatialAudio3D: '3D Spatial Audio Map',
  dragPlayerToExplore: 'Drag player icon around map to experience distance-based 3D audio.',
  audioCrossfadeActive: 'Crossfading soundtrack smoothly...',

  zoneLogin: 'Ethereal Beginnings (Login)',
  zoneCharSelect: "Heroes' Awakening (Char Select)",
  zoneVillage: 'Haven Rest (Safe Zone Village)',
  zoneForest: 'Emerald Canopy (Ancient Forest)',
  zoneSnow: 'Frostpeak Mountains (Glacial Peaks)',
  zoneDesert: 'Golden Dunes (Sunburn Desert)',
  zoneDungeon: 'Shadow Citadel (Dungeon Depths)',
  zoneCastle: 'Imperial Castle (Throne Room)',
  zoneBoss: 'Wrath of Titans (Boss Arena)',
  zoneRaid: 'Storm of Valors (Raid Dungeon)',
  zonePvP: "Gladiator's Clash (PvP Arena)",
  zoneGuild: 'Bards & Ale (Guild Hall)',
  zoneMarket: 'Bustling Bazaar (Marketplace)',

  ambBirds: 'Forest Birds',
  ambWind: 'Alpine Wind',
  ambRiver: 'Flowing River',
  ambWaves: 'Ocean Waves',
  ambRain: 'Gentle Rain',
  ambThunder: 'Distant Thunder',
  ambFireplace: 'Crackling Fire',
  ambInsects: 'Night Crickets',
  ambWaterfall: 'Waterfall Mist',
  ambSnowWind: 'Blizzard Howl',
  ambCaveEcho: 'Cave Drops',
  ambCrickets: 'Forest Insects',

  cloudSaveTitle: 'Cloud Sync & Cross-Platform Save',
  syncStatus: 'Sync Status',
  synced: 'Cloud Synced',
  syncing: 'Synchronizing...',
  offlineMode: 'Offline Cache Mode',
  lastCloudBackup: 'Last Cloud Backup',
  forceBackupNow: 'Force Backup Now',
  conflictResolutionTitle: 'Cloud Save Conflict Detected',
  conflictResolutionDesc: 'Your local save data differs from the cloud backup. Select which save file to preserve.',
  serverSave: 'Server Cloud Save',
  localSave: 'Local Browser Cache',
  keepServerSave: 'Use Cloud Save',
  keepLocalSave: 'Overwrite Cloud with Local Save',

  securityTitle: 'Security, JWT & Encryption Overview',
  jwtTokenStatus: 'JWT Access & Refresh Token',
  bcryptHashMethod: 'Password Hashing (bcrypt)',
  csrfProtected: 'CSRF & Rate Limit Active',
  rateLimitProtected: 'Server Rate Limiter',

  saveSuccess: 'Settings saved successfully!',
  actionCancelled: 'Action cancelled.',
  close: 'Close',
  confirm: 'Confirm',
  cancel: 'Cancel',
};

const id: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Sistem RPG & Akun Multibahasa',
  navHome: 'Ikhtisar',
  navLogin: 'Akun & Masuk',
  navCharacters: 'Karakter',
  navAudio: 'Musik & Suara',
  navSecurity: 'Keamanan & JWT',
  navCloud: 'Simpanan Awan',
  navSettings: 'Pengaturan',

  selectLanguageTitle: 'Pilih Bahasa Anda',
  selectLanguageDesc: 'Pilih bahasa tampilan untuk UI, dialog, dan pesan sistem.',
  confirmLanguage: 'Konfirmasi & Lanjutkan',
  changeLanguageAnytime: 'Anda dapat mengubah bahasa kapan saja di Pengaturan tanpa restart.',
  currentLanguage: 'Bahasa Saat Ini',
  voiceOverLanguage: 'Bahasa Pengisi Suara',
  subtitleLanguage: 'Bahasa Teks Terjemahan',
  formattingPreview: 'Pratinjau Format Lokal',
  sampleDate: 'Tanggal Format',
  sampleCurrency: 'Mata Uang Format',
  sampleNumber: 'Jumlah Emas',

  loginTitle: 'Otentikasi Akun',
  registerTitle: 'Buat Akun Baru',
  guestLogin: 'Main Cepat sebagai Tamu',
  emailLabel: 'Alamat Email',
  passwordLabel: 'Kata Sandi',
  rememberMe: 'Ingat Saya',
  forgotPassword: 'Lupa Kata Sandi?',
  loginButton: 'Masuk',
  registerButton: 'Daftar Akun',
  logoutButton: 'Keluar',
  socialLoginOr: 'atau hubungkan dengan',
  loginWithGoogle: 'Google',
  loginWithApple: 'Apple ID',
  loginWithFacebook: 'Facebook',
  loginWithDiscord: 'Discord',
  twoFactorAuth: 'Otentikasi Dua-Faktor (2FA)',
  enter2FACode: 'Masukkan Kode Otentikator 6-Digit',
  verify2FA: 'Verifikasi & Masuk',
  sendResetLink: 'Kirim Email Atur Ulang',
  resetPasswordTitle: 'Atur Ulang Kata Sandi',
  enterVerificationCode: 'Masukkan Kode Verifikasi',
  accountLockedTitle: 'Akun Dikunci Sementara',
  accountLockedDesc: 'Terlalu banyak percobaan gagal. Silakan coba lagi setelah jeda waktu.',
  rateLimitWarning: 'Peringatan Batas Laju: Terlalu banyak permintaan. Jeda aktif.',
  guestNotice: 'Bermain sebagai Tamu. Kemajuan disimpan lokal. Hubungkan email atau akun sosial untuk Sinkronisasi Awan.',

  sessionManagement: 'Manajemen Sesi & Perangkat',
  activeDevices: 'Perangkat Aktif Terhubung',
  currentDevice: 'Perangkat Ini (Aktif)',
  revokeSession: 'Cabut Sesi',
  revokeAllSessions: 'Keluar Dari Semua Perangkat Lain',
  lastActive: 'Terakhir Aktif',
  ipAddress: 'Alamat IP',

  characterSelectTitle: 'Pusat Karakter',
  createCharacter: 'Buat Karakter',
  deleteCharacter: 'Hapus Karakter',
  deleteConfirmationTitle: 'Konfirmasi Penghapusan Karakter',
  deleteConfirmationDesc: 'Tindakan ini tidak dapat dibatalkan. Seluruh item dan level akan dihapus.',
  typeCharacterNameToConfirm: 'Ketik nama karakter untuk konfirmasi:',
  renameTicketTitle: 'Tiket Ganti Nama Karakter',
  useRenameTicket: 'Gunakan Tiket Ganti Nama',
  newCharacterName: 'Masukkan Nama Karakter Baru',
  characterClass: 'Kelas',
  level: 'Level',
  stats: 'Atribut & Status Tempur',
  customizeAppearance: 'Kustomisasi Visual',
  hairColor: 'Gaya & Warna Rambut',
  outfitColor: 'Warna Pakaian & Zirah',
  weaponGlow: 'Efek Kilau Senjata',
  serverSelect: 'Server / Server Realm',

  audioSettingsTitle: 'Mesin Musik & Suara Adaptif',
  masterVolume: 'Volume Utama',
  musicVolume: 'Volume Musik',
  ambientVolume: 'Suara Lingkungan',
  voiceVolume: 'Volume Suara',
  uiVolume: 'Volume Efek UI',
  currentZone: 'Wilayah / Zona Aktif',
  selectZone: 'Ganti Musik Wilayah',
  musicStyle: 'Gaya Musik Saat Ini',
  ambientSounds: 'Lapisan Suara Sekitar',
  environmentalReverb: 'Gema Lingkungan',
  spatialAudio3D: 'Peta Suara Spasial 3D',
  dragPlayerToExplore: 'Geser ikon pemain di peta untuk merasakan suara 3D berdasarkan jarak.',
  audioCrossfadeActive: 'Mengubah musik dengan mulus...',

  zoneLogin: 'Ethereal Beginnings (Lobi)',
  zoneCharSelect: 'Heroes Awakening (Pilih Karakter)',
  zoneVillage: 'Haven Rest (Desa Aman)',
  zoneForest: 'Emerald Canopy (Hutan Kuno)',
  zoneSnow: 'Frostpeak Mountains (Gunung Salju)',
  zoneDesert: 'Golden Dunes (Gurun Pasir)',
  zoneDungeon: 'Shadow Citadel (Bawah Tanah)',
  zoneCastle: 'Imperial Castle (Istana Kerajaan)',
  zoneBoss: 'Wrath of Titans (Arena Bos)',
  zoneRaid: 'Storm of Valors (Raid Dungeon)',
  zonePvP: 'Gladiators Clash (Arena PvP)',
  zoneGuild: 'Bards & Ale (Aula Guild)',
  zoneMarket: 'Bustling Bazaar (Pasar)',

  ambBirds: 'Burung Hutan',
  ambWind: 'Angin Pegunungan',
  ambRiver: 'Aliran Sungai',
  ambWaves: 'Ombak Laut',
  ambRain: 'Hujan Lembut',
  ambThunder: 'Guruh Jauh',
  ambFireplace: 'Api Unggun',
  ambInsects: 'Jangkrik Malam',
  ambWaterfall: 'Air Terjun',
  ambSnowWind: 'Badai Salju',
  ambCaveEcho: 'Tetesan Gua',
  ambCrickets: 'Serangga Hutan',

  cloudSaveTitle: 'Sinkronisasi Awan & Lintas Platform',
  syncStatus: 'Status Sinkronisasi',
  synced: 'Tersinkronisasi Awan',
  syncing: 'Menyinkronkan...',
  offlineMode: 'Mode Cache Offline',
  lastCloudBackup: 'Pencadangan Awan Terakhir',
  forceBackupNow: 'Paksa Cadangkan Sekarang',
  conflictResolutionTitle: 'Konflik Data Awan Terdeteksi',
  conflictResolutionDesc: 'Data lokal Anda berbeda dengan cadangan awan. Pilih simpanan yang ingin digunakan.',
  serverSave: 'Simpanan Awan Server',
  localSave: 'Cache Lokal Peramban',
  keepServerSave: 'Gunakan Simpanan Awan',
  keepLocalSave: 'Timpa Awan dengan Data Lokal',

  securityTitle: 'Gambaran Keamanan & JWT',
  jwtTokenStatus: 'Token Akses JWT & Refresh',
  bcryptHashMethod: 'Enkripsi Kata Sandi (bcrypt)',
  csrfProtected: 'Perlindungan CSRF Aktif',
  rateLimitProtected: 'Pembatas Laju Server',

  saveSuccess: 'Pengaturan berhasil disimpan!',
  actionCancelled: 'Tindakan dibatalkan.',
  close: 'Tutup',
  confirm: 'Konfirmasi',
  cancel: 'Batal',
};

const ja: TranslationDictionary = {
  ...en,
  appName: 'エーテリア・オンライン',
  appSubtitle: '多言語対応ファンタジーRPGエンジン',
  navHome: '概要',
  navLogin: 'アカウント＆ログイン',
  navCharacters: 'キャラクター',
  navAudio: 'オーディオ＆BGM',
  navSecurity: 'セキュリティ＆JWT',
  navCloud: 'クラウドセーブ',
  navSettings: 'ゲーム設定',

  selectLanguageTitle: '言語を選択してください',
  selectLanguageDesc: 'UI、会話、システムメッセージの表示言語を選択します。',
  confirmLanguage: '決定して次へ',
  changeLanguageAnytime: '設定画面からいつでも再起動なしで変更できます。',
  currentLanguage: '現在の言語',
  voiceOverLanguage: 'ボイス言語',
  subtitleLanguage: '字幕言語',
  formattingPreview: '地域フォーマットのプレビュー',
  sampleDate: 'フォーマット済み日付',
  sampleCurrency: 'フォーマット済み通貨',
  sampleNumber: '所持ゴールド',

  loginTitle: 'アカウント認証',
  registerTitle: '新規アカウント作成',
  guestLogin: 'ゲストとして即時プレイ',
  emailLabel: 'メールアドレス',
  passwordLabel: 'パスワード',
  rememberMe: 'ログイン状態を保存',
  forgotPassword: 'パスワードをお忘れですか？',
  loginButton: 'ログイン',
  registerButton: 'アカウント登録',
  logoutButton: 'ログアウト',
  socialLoginOr: 'またはSNSで連携',
  loginWithGoogle: 'Google',
  loginWithApple: 'Apple ID',
  loginWithFacebook: 'Facebook',
  loginWithDiscord: 'Discord',
  twoFactorAuth: '2段階認証 (2FA)',
  enter2FACode: '6桁の認証コードを入力',
  verify2FA: '認証してログイン',
  sendResetLink: '再設定メールを送信',
  resetPasswordTitle: 'パスワード再設定',
  enterVerificationCode: '確認コードを入力',
  accountLockedTitle: 'アカウント一時ロック',
  accountLockedDesc: '失敗回数が多すぎます。クールダウン終了後にお試しください。',
  rateLimitWarning: 'レート制限警告: リクエストが多すぎます。',
  guestNotice: 'ゲストモードでプレイ中。進行状況はローカルに保存されます。',

  sessionManagement: 'セッション＆デバイス管理',
  activeDevices: 'アクティブな接続デバイス',
  currentDevice: 'このデバイス（現在）',
  revokeSession: 'セッション解除',
  revokeAllSessions: '他の全デバイスからログアウト',
  lastActive: '最終アクティブ',
  ipAddress: 'IPアドレス',

  characterSelectTitle: 'キャラクター選択ハブ',
  createCharacter: 'キャラ作成',
  deleteCharacter: 'キャラ削除',
  deleteConfirmationTitle: 'キャラクター削除の確認',
  deleteConfirmationDesc: 'この操作は取り消せません。アイテムとレベルは消去されます。',
  typeCharacterNameToConfirm: '確認のためにキャラクター名を入力:',
  renameTicketTitle: '名前変更チケット',
  useRenameTicket: 'チケットを使用して改名',
  newCharacterName: '新しいキャラクター名を入力',
  characterClass: '職業',
  level: 'レベル',
  stats: 'ステータス',
  customizeAppearance: '外見カスタマイズ',
  hairColor: '髪型＆髪色',
  outfitColor: '衣装・防具カラー',
  weaponGlow: 'オーラ・武器の光',
  serverSelect: 'ワールド／サーバー',

  audioSettingsTitle: 'アダプティブBGM＆環境音エンジン',
  masterVolume: '主音量 (Master)',
  musicVolume: 'BGM音量',
  ambientVolume: '環境音音量',
  voiceVolume: 'ボイス音量',
  uiVolume: 'UI効果音',
  currentZone: '現在の地域・ゾーン',
  selectZone: 'BGMテーマを変更',
  musicStyle: '現在の演奏スタイル',
  ambientSounds: '環境音レイヤー',
  environmentalReverb: '空間リバーブ効果',
  spatialAudio3D: '3D立体音響マップ',
  dragPlayerToExplore: 'プレイヤーアイコンをドラッグして距離に応じた3Dサウンドを体感できます。',
  audioCrossfadeActive: 'BGMを滑らかにクロスフェード中...',

  zoneLogin: 'スタート画面 (ログイン)',
  zoneCharSelect: '英雄の目覚め (キャラ選択)',
  zoneVillage: '安らぎの村 (安全地帯)',
  zoneForest: 'エメラルドの森 (古代森林)',
  zoneSnow: 'フロストピーク山脈 (雪山)',
  zoneDesert: '黄金の砂丘 (砂漠)',
  zoneDungeon: '影の城塞 (ダンジョン深部)',
  zoneCastle: 'インペリアルキャッスル (玉座)',
  zoneBoss: '巨神の怒り (ボスアリーナ)',
  zoneRaid: '勇者の嵐 (レイドダンジョン)',
  zonePvP: '剣闘士の闘技場 (PvP)',
  zoneGuild: '酒場と詩人 (ギルドホール)',
  zoneMarket: '賑わうバザール (市場)',

  ambBirds: '森の小鳥',
  ambWind: '高山の風',
  ambRiver: '川のせせらぎ',
  ambWaves: '波の音',
  ambRain: '静かな雨',
  ambThunder: '遠くの雷鳴',
  ambFireplace: '暖炉の焚き火',
  ambInsects: '秋の鈴虫',
  ambWaterfall: '滝の水音',
  ambSnowWind: '吹雪の地鳴り',
  ambCaveEcho: '洞窟の水滴',
  ambCrickets: '夜の虫の声',

  cloudSaveTitle: 'クラウド同期＆クロスプラットフォーム',
  syncStatus: '同期ステータス',
  synced: 'クラウド同期済み',
  syncing: '同期中...',
  offlineMode: 'オフラインキャッシュモード',
  lastCloudBackup: '最終クラウドバックアップ',
  forceBackupNow: '今すぐバックアップ実行',
  conflictResolutionTitle: 'セーブデータの競合検出',
  conflictResolutionDesc: 'ローカルデータとクラウドデータの差分があります。使用するデータを選択してください。',
  serverSave: 'クラウドセーブ（サーバー）',
  localSave: 'ローカルセーブ（端末）',
  keepServerSave: 'クラウドデータを使用',
  keepLocalSave: 'ローカルでクラウドを上書き',

  securityTitle: 'セキュリティとJWT認証',
  jwtTokenStatus: 'JWTアクセストークン＆リフレッシュ',
  bcryptHashMethod: 'パスワード暗号化 (bcrypt)',
  csrfProtected: 'CSRF保護＆レート制限',
  rateLimitProtected: 'サーバーレートリミッター',

  saveSuccess: '設定を保存しました。',
  actionCancelled: 'キャンセルされました。',
  close: '閉じる',
  confirm: '確定',
  cancel: 'キャンセル',
};

const ko: TranslationDictionary = {
  ...en,
  appName: '에테리아 온라인',
  appSubtitle: '다국어 지원 판타지 RPG 엔진',
  navHome: '개요',
  navLogin: '계정 및 로그인',
  navCharacters: '캐릭터',
  navAudio: '오디오 및 BGM',
  navSecurity: '보안 및 JWT',
  navCloud: '클라우드 저장',
  navSettings: '게임 설정',

  selectLanguageTitle: '언어를 선택하세요',
  selectLanguageDesc: 'UI, 대화, 시스템 메시지에 사용할 언어를 선택합니다.',
  confirmLanguage: '확인 및 계속',
  changeLanguageAnytime: '재시작 없이 설정에서 언제든지 변경할 수 있습니다.',
  currentLanguage: '현재 언어',
  voiceOverLanguage: '음성 언어',
  subtitleLanguage: '자막 언어',
  formattingPreview: '지역 형식 미리보기',
  sampleDate: '형식화된 날짜',
  sampleCurrency: '형식화된 통화',
  sampleNumber: '소지 골드',

  loginTitle: '계정 인증',
  registerTitle: '새 계정 생성',
  guestLogin: '게스트 빠른 플레이',
  emailLabel: '이메일 주소',
  passwordLabel: '비밀번호',
  rememberMe: '로그인 상태 유지',
  forgotPassword: '비밀번호를 잊으셨나요?',
  loginButton: '로그인',
  registerButton: '계정 등록',
  logoutButton: '로그아웃',
  socialLoginOr: '또는 소셜 계정으로 로그인',
  loginWithGoogle: 'Google',
  loginWithApple: 'Apple ID',
  loginWithFacebook: 'Facebook',
  loginWithDiscord: 'Discord',
  twoFactorAuth: '2단계 인증 (2FA)',
  enter2FACode: '6자리 인증 코드를 입력하세요',
  verify2FA: '인증 및 로그인',
  sendResetLink: '재설정 이메일 발송',
  resetPasswordTitle: '비밀번호 재설정',
  enterVerificationCode: '인증 코드 입력',
  accountLockedTitle: '계정 일시 잠금',
  accountLockedDesc: '시도 횟수가 초과되었습니다. 쿨다운 후 다시 시도하세요.',
  rateLimitWarning: '요청 제한 경고: 너무 많은 요청이 발생했습니다.',
  guestNotice: '게스트 모드로 플레이 중입니다. 진행 상황은 로컬에 저장됩니다.',

  sessionManagement: '세션 및 기기 관리',
  activeDevices: '현재 로그인된 기기',
  currentDevice: '현재 기기',
  revokeSession: '세션 해제',
  revokeAllSessions: '다른 모든 기기에서 로그아웃',
  lastActive: '최근 활동',
  ipAddress: 'IP 주소',

  characterSelectTitle: '캐릭터 선택 센터',
  createCharacter: '캐릭터 생성',
  deleteCharacter: '캐릭터 삭제',
  deleteConfirmationTitle: '캐릭터 삭제 확인',
  deleteConfirmationDesc: '이 작업은 되돌릴 수 없습니다. 모든 아이템과 레벨이 삭제됩니다.',
  typeCharacterNameToConfirm: '확인을 위해 캐릭터 이름을 입력하세요:',
  renameTicketTitle: '이름 변경권',
  useRenameTicket: '이름 변경권 사용',
  newCharacterName: '새 캐릭터 이름 입력',
  characterClass: '직업',
  level: '레벨',
  stats: '능력치 및 전투 스탯',
  customizeAppearance: '외형 커스터마이징',
  hairColor: '헤어 스타일 및 색상',
  outfitColor: '의상 및 방어구 색상',
  weaponGlow: '무기 광원 효과',
  serverSelect: '서버 / 월드',

  audioSettingsTitle: '적응형 음악 및 오디오 엔진',
  masterVolume: '마스터 음량',
  musicVolume: 'BGM 음량',
  ambientVolume: '환경음 음량',
  voiceVolume: '음성 음량',
  uiVolume: 'UI 효과음',
  currentZone: '현재 지역 / 존',
  selectZone: '지역 BGM 변경',
  musicStyle: '현재 음악 스타일',
  ambientSounds: '환경음 레이어',
  environmentalReverb: '공간 리버브 효과',
  spatialAudio3D: '3D 입체 음향 맵',
  dragPlayerToExplore: '플레이어 아이콘을 드래그하여 거리 기반 3D 입체 사운드를 체감하세요.',
  audioCrossfadeActive: 'BGM을 부드럽게 전환 중...',

  zoneLogin: '시작 화면 (로그인)',
  zoneCharSelect: '영웅의 각성 (캐릭터 선택)',
  zoneVillage: '안식의 마을 (안전 지대)',
  zoneForest: '에메랄드 숲 (고대 산림)',
  zoneSnow: '서리봉 산맥 (설산)',
  zoneDesert: '황금 사구 (사막)',
  zoneDungeon: '그림자 요새 (던전 심부)',
  zoneCastle: '임페리얼 캐슬 (알현실)',
  zoneBoss: '거신의 분노 (보스 아레나)',
  zoneRaid: '용사의 폭풍 (레이드 던전)',
  zonePvP: '글래디에이터 아레나 (PvP)',
  zoneGuild: '길드 홀 (시인과 술집)',
  zoneMarket: '시끌벅적한 바자회 (시장)',

  ambBirds: '숲속 새소리',
  ambWind: '고산 바람',
  ambRiver: '강물 소리',
  ambWaves: '파도 소리',
  ambRain: '부드러운 빗소리',
  ambThunder: '아득한 천둥',
  ambFireplace: '모닥불 타는 소리',
  ambInsects: '밤 귀뚜라미',
  ambWaterfall: '폭포 소리',
  ambSnowWind: '눈보라 소리',
  ambCaveEcho: '동굴 물방울',
  ambCrickets: '풀벌레 소리',

  cloudSaveTitle: '클라우드 동기화 및 크로스 플랫폼',
  syncStatus: '동기화 상태',
  synced: '클라우드 동기화 완료',
  syncing: '동기화 중...',
  offlineMode: '오프라인 캐시 모드',
  lastCloudBackup: '최근 클라우드 백업',
  forceBackupNow: '지금 수동 백업',
  conflictResolutionTitle: '클라우드 저장 충돌 감지',
  conflictResolutionDesc: '로컬 데이터와 클라우드 데이터가 다릅니다. 사용할 저장 파일을 선택하세요.',
  serverSave: '클라우드 저장 (서버)',
  localSave: '로컬 캐시 (기기)',
  keepServerSave: '클라우드 데이터 사용',
  keepLocalSave: '로컬 데이터로 덮어쓰기',

  securityTitle: '보안 및 JWT 시스템',
  jwtTokenStatus: 'JWT 액세스 & 리프레시 토큰',
  bcryptHashMethod: '비밀번호 암호화 (bcrypt)',
  csrfProtected: 'CSRF 및 요청 제한 활성화',
  rateLimitProtected: '서버 요청 제한기',

  saveSuccess: '설정이 저장되었습니다.',
  actionCancelled: '취소되었습니다.',
  close: '닫기',
  confirm: '확인',
  cancel: '취소',
};

const zhCN: TranslationDictionary = {
  ...en,
  appName: '以太之境 Online',
  appSubtitle: '多语言魔幻RPG引擎与账号系统',
  navHome: '概览',
  navLogin: '账号与登录',
  navCharacters: '角色管理',
  navAudio: '音乐与音效',
  navSecurity: '安全与JWT',
  navCloud: '云存档同步',
  navSettings: '游戏设置',

  selectLanguageTitle: '选择您的语言',
  selectLanguageDesc: '选择UI界面、剧情对话与系统消息的显示语言。',
  confirmLanguage: '确认并继续',
  changeLanguageAnytime: '您可以在设置中随时切换语言，无需重启游戏。',
  currentLanguage: '当前语言',
  voiceOverLanguage: '语音语言',
  subtitleLanguage: '字幕语言',
  formattingPreview: '本地化格式预览',
  sampleDate: '格式化日期',
  sampleCurrency: '格式化货币',
  sampleNumber: '拥有金币',

  loginTitle: '账号身份验证',
  registerTitle: '创建新账号',
  guestLogin: '游客快速试玩',
  emailLabel: '电子邮箱',
  passwordLabel: '密码',
  rememberMe: '记住登录状态',
  forgotPassword: '忘记密码？',
  loginButton: '登录',
  registerButton: '注册账号',
  logoutButton: '退出登录',
  socialLoginOr: '或使用快捷登录',
  loginWithGoogle: 'Google',
  loginWithApple: 'Apple ID',
  loginWithFacebook: 'Facebook',
  loginWithDiscord: 'Discord',
  twoFactorAuth: '双重身份验证 (2FA)',
  enter2FACode: '请输入6位验证码',
  verify2FA: '验证并登录',
  sendResetLink: '发送重置邮件',
  resetPasswordTitle: '重置您的密码',
  enterVerificationCode: '输入验证码',
  accountLockedTitle: '账号已临时锁定',
  accountLockedDesc: '失败次数过多，请在冷却倒计时结束后重试。',
  rateLimitWarning: '请求频率警告：请求过于频繁，触发冷却。',
  guestNotice: '当前为游客模式。进度保存在本地，绑定账号后可启用云同步。',

  sessionManagement: '会话与设备管理',
  activeDevices: '已登录设备列表',
  currentDevice: '当前设备',
  revokeSession: '注销该设备',
  revokeAllSessions: '注销所有其他设备',
  lastActive: '最后活跃时间',
  ipAddress: 'IP地址',

  characterSelectTitle: '角色选择中心',
  createCharacter: '创建角色',
  deleteCharacter: '删除角色',
  deleteConfirmationTitle: '确认删除角色',
  deleteConfirmationDesc: '此操作无法撤销。该角色的等级与物品将被彻底清除。',
  typeCharacterNameToConfirm: '输入角色名称以确认删除：',
  renameTicketTitle: '角色改名卡',
  useRenameTicket: '使用改名卡',
  newCharacterName: '输入新角色名称',
  characterClass: '职业',
  level: '等级',
  stats: '属性与战斗数值',
  customizeAppearance: '外观自定义',
  hairColor: '发型与发色',
  outfitColor: '服装与护甲染色',
  weaponGlow: '武器特效光武',
  serverSelect: '服务器／大区',

  audioSettingsTitle: '自适应音乐与环境音效引擎',
  masterVolume: '主音量',
  musicVolume: '背景音乐音量',
  ambientVolume: '环境音效音量',
  voiceVolume: '语音音量',
  uiVolume: '界面音效音量',
  currentZone: '当前区域／地图',
  selectZone: '切换区域音乐主题',
  musicStyle: '当前演奏风格',
  ambientSounds: '环境音效图层',
  environmentalReverb: '空间混响效果',
  spatialAudio3D: '3D空间音频地图',
  dragPlayerToExplore: '拖动角色图标感受基于距离的3D环绕立体声。',
  audioCrossfadeActive: '正在平滑淡入淡出切换音乐...',

  zoneLogin: '初识以太 (登录界面)',
  zoneCharSelect: '英雄觉醒 (角色选择)',
  zoneVillage: '庇护之村 (安全区)',
  zoneForest: '翡翠树冠 (古老森林)',
  zoneSnow: '霜峰山脉 (雪山)',
  zoneDesert: '黄金沙丘 (沙漠)',
  zoneDungeon: '暗影堡垒 (地牢深处)',
  zoneCastle: '帝王城堡 (王座大厅)',
  zoneBoss: '巨神之怒 (BOSS竞技场)',
  zoneRaid: '勇士风暴 (团队副本)',
  zonePvP: '角斗士竞技场 (PvP)',
  zoneGuild: '吟游酒馆 (公会大厅)',
  zoneMarket: '喧嚣巴扎 (集市)',

  ambBirds: '森林鸟鸣',
  ambWind: '高山呼啸',
  ambRiver: '潺潺流水',
  ambWaves: '海洋波涛',
  ambRain: '细雨绵绵',
  ambThunder: '远处惊雷',
  ambFireplace: '篝火噼啪',
  ambInsects: '夜间蟋蟀',
  ambWaterfall: '飞瀑流泉',
  ambSnowWind: '暴风雪声',
  ambCaveEcho: '溶洞水滴',
  ambCrickets: '丛林虫鸣',

  cloudSaveTitle: '云端同步与跨平台存档',
  syncStatus: '同步状态',
  synced: '云端已同步',
  syncing: '正在同步...',
  offlineMode: '离线缓存模式',
  lastCloudBackup: '上次云端备份',
  forceBackupNow: '立即强制备份',
  conflictResolutionTitle: '检测到云存档冲突',
  conflictResolutionDesc: '本地缓存与云端备份存在差异，请选择保留的存档。',
  serverSave: '云端存档（服务器）',
  localSave: '本地缓存（设备）',
  keepServerSave: '使用云端存档',
  keepLocalSave: '用本地覆盖云端',

  securityTitle: '安全机制与JWT鉴权',
  jwtTokenStatus: 'JWT Access & Refresh Token',
  bcryptHashMethod: '密码加密 (bcrypt)',
  csrfProtected: 'CSRF防护与频率限制',
  rateLimitProtected: '服务器速率限制器',

  saveSuccess: '设置已成功保存！',
  actionCancelled: '操作已取消。',
  close: '关闭',
  confirm: '确认',
  cancel: '取消',
};

const zhTW: TranslationDictionary = {
  ...zhCN,
  appName: '以太之境 Online',
  appSubtitle: '多語言魔幻RPG引擎與帳號系統',
  navHome: '概覽',
  navLogin: '帳號與登入',
  navCharacters: '角色管理',
  navAudio: '音樂與音效',
  navSecurity: '安全與JWT',
  navCloud: '雲端存檔同步',
  navSettings: '遊戲設定',

  selectLanguageTitle: '選擇您的語言',
  selectLanguageDesc: '選擇UI介面、劇情對話與系統訊息的顯示語言。',
  confirmLanguage: '確認並繼續',
  changeLanguageAnytime: '您可以在設定中隨時切換語言，無需重啟遊戲。',
  currentLanguage: '當前語言',
  voiceOverLanguage: '語音語言',
  subtitleLanguage: '字幕語言',
  loginTitle: '帳號身份驗證',
  registerTitle: '創建新帳號',
  guestLogin: '遊客快速試玩',
  loginButton: '登入',
  registerButton: '註冊帳號',
  logoutButton: '登出',
  close: '關閉',
  confirm: '確認',
  cancel: '取消',
};

const es: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Motor RPG y Sistema de Cuentas Multilingüe',
  navHome: 'Resumen',
  navLogin: 'Cuenta e Inicio',
  navCharacters: 'Personajes',
  navAudio: 'Audio y Música',
  navSecurity: 'Seguridad y JWT',
  navCloud: 'Guardado en la Nube',
  navSettings: 'Ajustes de Juego',

  selectLanguageTitle: 'Seleccione su Idioma',
  selectLanguageDesc: 'Elija su idioma preferido para la interfaz, diálogos y mensajes del sistema.',
  confirmLanguage: 'Confirmar y Continuar',
  changeLanguageAnytime: 'Puede cambiar el idioma en Ajustes en cualquier momento sin reiniciar.',
  currentLanguage: 'Idioma Actual',
  voiceOverLanguage: 'Idioma de Voz',
  subtitleLanguage: 'Idioma de Subtítulos',

  loginTitle: 'Autenticación de Cuenta',
  registerTitle: 'Crear Nueva Cuenta',
  guestLogin: 'Jugar como Invitado',
  emailLabel: 'Correo Electrónico',
  passwordLabel: 'Contraseña',
  rememberMe: 'Recordarme',
  forgotPassword: '¿Olvidó su contraseña?',
  loginButton: 'Iniciar Sesión',
  registerButton: 'Registrarse',
  logoutButton: 'Cerrar Sesión',

  characterSelectTitle: 'Centro de Selección de Personajes',
  createCharacter: 'Crear Personaje',
  deleteCharacter: 'Eliminar Personaje',

  audioSettingsTitle: 'Motor de Música Adaptativa y Audio',
  masterVolume: 'Volumen Principal',
  musicVolume: 'Volumen de Música',
  ambientVolume: 'Efectos de Ambiente',

  cloudSaveTitle: 'Guardado en la Nube y Sincronización',
  saveSuccess: '¡Ajustes guardados correctamente!',
  close: 'Cerrar',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
};

const pt: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Engine RPG e Sistema de Contas Multilíngue',
  navHome: 'Visão Geral',
  navLogin: 'Conta e Login',
  navCharacters: 'Personagens',
  navAudio: 'Áudio e Música',
  navSecurity: 'Segurança e JWT',
  navCloud: 'Nuvem e Sincronização',
  navSettings: 'Configurações',

  selectLanguageTitle: 'Selecione Seu Idioma',
  selectLanguageDesc: 'Escolha seu idioma preferido para a interface, diálogos e mensagens.',
  confirmLanguage: 'Confirmar e Continuar',
  changeLanguageAnytime: 'Você pode alterar o idioma nas Configurações a qualquer momento sem reiniciar.',
  currentLanguage: 'Idioma Atual',
  voiceOverLanguage: 'Idioma de Dublagem',
  subtitleLanguage: 'Idioma de Legendagem',

  loginTitle: 'Autenticação de Conta',
  registerTitle: 'Criar Nova Conta',
  guestLogin: 'Jogar como Convidado',
  loginButton: 'Entrar',
  registerButton: 'Registrar',
  logoutButton: 'Sair',

  saveSuccess: 'Configurações salvas com sucesso!',
  close: 'Fechar',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
};

const fr: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Moteur RPG et Système de Compte Multilingue',
  navHome: 'Aperçu',
  navLogin: 'Compte & Connexion',
  navCharacters: 'Personnages',
  navAudio: 'Audio & Musique',
  navSecurity: 'Sécurité & JWT',
  navCloud: 'Sauvegarde Cloud',
  navSettings: 'Paramètres',

  selectLanguageTitle: 'Choisissez Votre Langue',
  selectLanguageDesc: 'Sélectionnez votre langue pour l\'interface, les dialogues et le système.',
  confirmLanguage: 'Confirmer & Continuer',
  changeLanguageAnytime: 'Vous pouvez changer de langue à tout moment dans les Paramètres.',
  currentLanguage: 'Langue Actuelle',
  voiceOverLanguage: 'Langue de Doublage',
  subtitleLanguage: 'Langue des Sous-titres',

  loginTitle: 'Authentification du Compte',
  registerTitle: 'Créer un Compte',
  guestLogin: 'Jouer en Invité',
  loginButton: 'Se Connecter',
  registerButton: 'S\'inscrire',
  logoutButton: 'Se Déconnecter',

  saveSuccess: 'Paramètres enregistrés avec succès !',
  close: 'Fermer',
  confirm: 'Confirmer',
  cancel: 'Annuler',
};

const de: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Mehrsprachige RPG Engine & Kontosystem',
  navHome: 'Übersicht',
  navLogin: 'Konto & Anmelden',
  navCharacters: 'Charaktere',
  navAudio: 'Audio & Musik',
  navSecurity: 'Sicherheit & JWT',
  navCloud: 'Cloud-Speicher',
  navSettings: 'Einstellungen',

  selectLanguageTitle: 'Wählen Sie Ihre Sprache',
  selectLanguageDesc: 'Wählen Sie Ihre bevorzugte Sprache für Benutzeroberfläche und Dialoge.',
  confirmLanguage: 'Bestätigen & Fortfahren',
  changeLanguageAnytime: 'Sie können die Sprache jederzeit in den Einstellungen ändern.',
  currentLanguage: 'Aktuelle Sprache',
  voiceOverLanguage: 'Sprachausgabe',
  subtitleLanguage: 'Untertitel-Sprache',

  loginTitle: 'Konto-Authentifizierung',
  registerTitle: 'Neues Konto Erstellen',
  guestLogin: 'Als Gast Spielen',
  loginButton: 'Anmelden',
  registerButton: 'Registrieren',
  logoutButton: 'Abmelden',

  saveSuccess: 'Einstellungen erfolgreich gespeichert!',
  close: 'Schließen',
  confirm: 'Bestätigen',
  cancel: 'Abbrechen',
};

const ru: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Многоязычный RPG Движок и Система Аккаунтов',
  navHome: 'Обзор',
  navLogin: 'Аккаунт и Вход',
  navCharacters: 'Персонажи',
  navAudio: 'Аудио и Музыка',
  navSecurity: 'Безопасность и JWT',
  navCloud: 'Облачные Сохранения',
  navSettings: 'Настройки Игры',

  selectLanguageTitle: 'Выберите Ваш Язык',
  selectLanguageDesc: 'Выберите предпочитаемый язык для интерфейса, диалогов и сообщений.',
  confirmLanguage: 'Подтвердить и Продолжить',
  changeLanguageAnytime: 'Вы можете изменить язык в Настройках в любое время без перезапуска.',
  currentLanguage: 'Текущий Язык',
  voiceOverLanguage: 'Язык Озвучки',
  subtitleLanguage: 'Язык Субтитров',

  loginTitle: 'Аутентификация Аккаунта',
  registerTitle: 'Создать Новый Аккаунт',
  guestLogin: 'Быстрая Игра как Гость',
  loginButton: 'Войти',
  registerButton: 'Зарегистрироваться',
  logoutButton: 'Выйти',

  saveSuccess: 'Настройки успешно сохранены!',
  close: 'Закрыть',
  confirm: 'Подтвердить',
  cancel: 'Отмена',
};

const ar: TranslationDictionary = {
  ...en,
  appName: 'إيثيريا أونلاين',
  appSubtitle: 'محرك ألعاب RPG ونظام حسابات متعدد اللغات',
  navHome: 'نظرة عامة',
  navLogin: 'الحساب وتسجيل الدخول',
  navCharacters: 'الشخصيات',
  navAudio: 'الصوت والموسيقى',
  navSecurity: 'الأمان و JWT',
  navCloud: 'الحفظ السحابي',
  navSettings: 'إعدادات اللعبة',

  selectLanguageTitle: 'اختر لغتك المفضلة',
  selectLanguageDesc: 'حدد اللغة المفضلة للواجهة والحوارات ورسائل النظام.',
  confirmLanguage: 'تأكيد والمتابعة',
  changeLanguageAnytime: 'يمكنك تغيير اللغة في أي وقت من الإعدادات دون إعادة تشغيل اللعبة.',
  currentLanguage: 'اللغة الحالية',
  voiceOverLanguage: 'لغة الأداء الصوتي',
  subtitleLanguage: 'لغة الترجمة',
  formattingPreview: 'معاينة التنسيق المحلي',
  sampleDate: 'التاريخ المنسق',
  sampleCurrency: 'العملة المنسقة',
  sampleNumber: 'الذهب المكتسب',

  loginTitle: 'مصادقة الحساب',
  registerTitle: 'إنشاء حساب جديد',
  guestLogin: 'اللعب السريع كضيف',
  emailLabel: 'البريد الإلكتروني',
  passwordLabel: 'كلمة المرور',
  rememberMe: 'تذكرني',
  forgotPassword: 'هل نسيت كلمة المرور؟',
  loginButton: 'تسجيل الدخول',
  registerButton: 'إنشاء حساب',
  logoutButton: 'تسجيل الخروج',

  characterSelectTitle: 'مركز اختيار الشخصيات',
  createCharacter: 'إنشاء شخصية',
  deleteCharacter: 'حذف الشخصية',

  audioSettingsTitle: 'محرك الموسيقى والتأثيرات الصوتية التكيفية',
  masterVolume: 'الصوت الرئيسي',
  musicVolume: 'صوت الموسيقى',
  ambientVolume: 'الأصوات المحيطة',

  cloudSaveTitle: 'المزامنة السحابية والحفظ عبر المنصات',
  saveSuccess: 'تم حفظ الإعدادات بنجاح!',
  close: 'إغلاق',
  confirm: 'تأكيد',
  cancel: 'إلغاء',
};

const th: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'เอนจินเกม RPG รองรับหลายภาษา',
  navHome: 'ภาพรวม',
  navLogin: 'บัญชีและการเข้าสู่ระบบ',
  navCharacters: 'ตัวละคร',
  navAudio: 'เสียงและดนตรี',
  navSecurity: 'ระบบความปลอดภัย & JWT',
  navCloud: 'บันทึกบนคลาวด์',
  navSettings: 'ตั้งค่าเกม',

  selectLanguageTitle: 'เลือกภาษาของคุณ',
  selectLanguageDesc: 'เลือกภาษาสำหรับการแสดงผล เมนู บทสนทนา และข้อความระบบ',
  confirmLanguage: 'ยืนยันและดำเนินการต่อ',
  changeLanguageAnytime: 'คุณสามารถเปลี่ยนภาษาได้ตลอดเวลาในเมนูตั้งค่าโดยไม่ต้องรีสตาร์ท',
  currentLanguage: 'ภาษาปัจจุบัน',
  voiceOverLanguage: 'ภาษาพากย์เสียง',
  subtitleLanguage: 'ภาษาคำบรรยาย',

  loginTitle: 'การยืนยันตัวตน',
  registerTitle: 'สร้างบัญชีใหม่',
  guestLogin: 'เล่นทันทีในฐานะแขก',
  loginButton: 'เข้าสู่ระบบ',
  registerButton: 'ลงทะเบียน',
  logoutButton: 'ออกจากระบบ',

  saveSuccess: 'บันทึกการตั้งค่าเรียบร้อยแล้ว!',
  close: 'ปิด',
  confirm: 'ยืนยัน',
  cancel: 'ยกเลิก',
};

const vi: TranslationDictionary = {
  ...en,
  appName: 'Aetheria Online',
  appSubtitle: 'Hệ Thống Game RPG Đa Ngôn Ngữ',
  navHome: 'Tổng Quan',
  navLogin: 'Tài Khoản & Đăng Nhập',
  navCharacters: 'Nhân Vật',
  navAudio: 'Âm Thanh & Âm Nhạc',
  navSecurity: 'Bảo Mật & JWT',
  navCloud: 'Lưu Cài Đặt Đám Mây',
  navSettings: 'Cài Đặt Game',

  selectLanguageTitle: 'Chọn Ngôn Ngữ Của Bạn',
  selectLanguageDesc: 'Chọn ngôn ngữ ưu tiên cho giao diện, thoại và tin nhắn hệ thống.',
  confirmLanguage: 'Xác Nhận & Tiếp Tục',
  changeLanguageAnytime: 'Bạn có thể thay đổi ngôn ngữ bất kỳ lúc nào trong Cài đặt mà không cần khởi động lại.',
  currentLanguage: 'Ngôn Ngữ Hiện Tại',
  voiceOverLanguage: 'Ngôn Ngữ Lồng Tiếng',
  subtitleLanguage: 'Ngôn Ngữ Phụ Đề',

  loginTitle: 'Xác Thực Tài Khoản',
  registerTitle: 'Tạo Tài Khoản Mới',
  guestLogin: 'Chơi Nhanh Với Tư Cách Khách',
  loginButton: 'Đăng Nhập',
  registerButton: 'Đăng Ký',
  logoutButton: 'Đăng Xuất',

  saveSuccess: 'Lưu cài đặt thành công!',
  close: 'Đóng',
  confirm: 'Xác Nhận',
  cancel: 'Hủy',
};

const dictionaries: Record<LanguageCode, TranslationDictionary> = {
  en,
  id,
  ja,
  ko,
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  es,
  pt,
  fr,
  de,
  ru,
  ar,
  th,
  vi,
};

export function getTranslation(lang: LanguageCode): TranslationDictionary {
  return dictionaries[lang] || dictionaries.en;
}

export function formatLocaleDate(date: Date, lang: LanguageCode): string {
  try {
    const langInfo = SUPPORTED_LANGUAGES.find(l => l.code === lang) || SUPPORTED_LANGUAGES[0];
    return new Intl.DateTimeFormat(lang, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).format(date);
  } catch (e) {
    return date.toISOString().split('T')[0];
  }
}

export function formatLocaleCurrency(amount: number, lang: LanguageCode): string {
  try {
    const langInfo = SUPPORTED_LANGUAGES.find(l => l.code === lang) || SUPPORTED_LANGUAGES[0];
    return new Intl.NumberFormat(lang, {
      style: 'currency',
      currency: langInfo.currency,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch (e) {
    return `$${amount.toLocaleString()}`;
  }
}

export function formatLocaleNumber(num: number, lang: LanguageCode): string {
  try {
    return new Intl.NumberFormat(lang).format(num);
  } catch (e) {
    return num.toString();
  }
}
